Updated the climatiq URLs in the python notebook
climatiq/examples pull request #5
Opened 2024-02-06 14:07 UTC by GeeWee

Notebook was still on the defunct beta3, now updated for GA release

2024-02-06 15:03 UTC, AnastasiaLobanova requested changes

2024-02-06 15:03 UTC, AnastasiaLobanova commented on notebooks/climatiq.ipynb
>      "If your data comes with an industry specification code Climatiq API allows you to query emission factors, based on their NACE or ISIC industry classification codes. At the moment this endpoint w
Suggest to edit in this way: If your data comes with an industry specification code Climatiq API allows you to query emission factors, based on their NACE, MCC or UNSPSC industry classification codes. At the moment this endpoint works only with spend-based dataset- EXIOBASE.


The ISIC codes are broken right, maybe we should remove them for now?

2024-02-07 12:20 UTC, GeeWee commented on notebooks/climatiq.ipynb
>      "If your data comes with an industry specification code Climatiq API allows you to query emission factors, based on their NACE or ISIC industry classification codes. At the moment this endpoint w
Edited, but I've kept ISIC. It's weird to say we do ISIC some places and not others. The ISIC codes might be a little broken, but some of them work, so let's say we support them. At some point it'll hopefully be right.

2024-02-08 08:32 UTC, AnastasiaLobanova commented on notebooks/climatiq.ipynb
>      "If your data comes with an industry specification code Climatiq API allows you to query emission factors, based on their NACE or ISIC industry classification codes. At the moment this endpoint w
Alright, agree!

2024-02-08 08:33 UTC, AnastasiaLobanova approved these changes

2024-02-08 09:23 UTC, merged